### ISSUE TITLE
regex test regressions in Node 0.10.x, 0.12.x and 4.x

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/uglify-es#8]
https://travis-ci.org/fabiosantoscode/uglify-es/jobs/370317034#L515
```
--- arrow.js
    Running test [arrow_functions_without_body]
    Running test [arrow_functions_with_body]
    Running test [arrow_function_with_single_parameter_with_default]
    Running test [arrow_binding_pattern]
    Running test [arrow_binding_pattern_strict]
    Running test [arrow_with_regexp]
!!! Cannot parse input
---INPUT---
{
    num => /\d{11,14}/undefined.test(num);
}
--PARSE ERROR--
SyntaxError: Invalid flags supplied to RegExp constructor 'undefined'
```

```
    Running test [collapse_vars_regexp]
!!! Cannot parse input
---INPUT---
{
    function f1() {
        var k = 9;
        var rx = /[A-Z]+/undefined;
        return [ rx, k ];
    }
    function f2() {
        var rx = /ab*/undefined;
        return function(s) {
            return rx.exec(s);
        };
    }
    (function() {
        var result;
        var s = 'acdabcdeabbb';
        var rx = /ab*/undefined;
        while (result = rx.exec(s)) {
            console.log(result[0]);
        }
    })();
    (function() {
        var result;
        var s = 'acdabcdeabbb';
        var rx = f2();
        while (result = rx(s)) {
            console.log(result[0]);
        }
    })();
}
--PARSE ERROR--
SyntaxError: Invalid flags supplied to RegExp constructor 'undefined'
```

```
    Running test [unused_regexp_literal]
!!! Cannot parse input
---INPUT---
{
    function f() {
        var a = /b/undefined;
    }
}
--PARSE ERROR--
SyntaxError: Invalid flags supplied to RegExp constructor 'undefined'
    Running test [regexp_literal_not_const]
!!! Cannot parse input
---INPUT---
{
    (function() {
        var result;
        const s = 'acdabcdeabbb';
        const REGEXP_LITERAL = /ab*/undefined;
        while (result = REGEXP_LITERAL.exec(s)) {
            console.log(result[0]);
        }
    })();
}
--PARSE ERROR--
SyntaxError: Invalid flags supplied to RegExp constructor 'undefined'
```

```
--- drop-unused.js
undefined:2
return({
^
SyntaxError: Invalid flags supplied to RegExp constructor 'undefined'
    at new RegExp (native)
    at eval (eval at <anonymous> (/home/travis/build/fabiosantoscode/uglify-es/test/run-tests.js:370:17), <anonymous>:2:1)
    at evaluate (/home/travis/build/fabiosantoscode/uglify-es/test/run-tests.js:388:48)
    at Object.visit (/home/travis/build/fabiosantoscode/uglify-es/test/run-tests.js:320:30)
    at Object.TreeWalker._visit (eval at <anonymous> (/home/travis/build/fabiosantoscode/uglify-es/test/node.js:1:0), <anonymous>:1526:24)
    at AST_Node.DEFNODE._walk (eval at <anonymous> (/home/travis/build/fabiosantoscode/uglify-es/test/node.js:1:0), <anonymous>:1172:24)
    at AST_Node.eval (eval at <anonymous> (/home/travis/build/fabiosantoscode/uglify-es/test/node.js:1:0), <anonymous>:502:23)
    at Object.TreeWalker._visit (eval at <anonymous> (/home/travis/build/fabiosantoscode/uglify-es/test/node.js:1:0), <anonymous>:1530:21)
    at AST_Node.DEFNODE._walk (eval at <anonymous> (/home/travis/build/fabiosantoscode/uglify-es/test/node.js:1:0), <anonymous>:501:24)
    at walk_body (eval at <anonymous> (/home/travis/build/fabiosantoscode/uglify-es/test/node.js:1:0), <anonymous>:513:17)
```

**Comment by kzc** [comment]
Appears to be fixed by https://github.com/fabiosantoscode/uglify-es/commit/6e9e1ec3ed37aeecf9d92ac887433cc960a94b9d in `@fabiosantoscode/uglify-es/3.6.0`
